---
#Available Modes: PurePerms and Hierarchy
Mode: PurePerms
#Toggle checking if a players Temporary Rank has expired every 60 seconds rather than only while joining the server
Check Rank Expiry every 60 seconds: true
#Message to send to Player's with a Temporary Rank on Join
Time Left Message: You have {time_left} on your temporary {temprank} rank
#Message to show to the Player once their Temporary Rank has expired
Rank Expired Message: Your {temprank} Rank has expired
...
